### PR TITLE
fix: no synthetic imports

### LINKED ISSUE #185: TypeError: method is not a function when calling request (regression from 0.20.1)
- OS: MacOS 10.13.5
  - Node.js version: 10.5.0
  - npm version: N/A
  - @google-cloud/common version: 0.20.2 (works on 0.20.1)

```js
await request({
  method: 'PUT',
  uri: `subscriptions/${this.name}`,
  body: {
    topic: `projects/${projectId}/topics/${topic}`,
    ackDeadlineSeconds: this.ackDeadlineSeconds,
  },
  json: true,
})
```

```
(node:1182) UnhandledPromiseRejectionWarning: TypeError: method is not a function
    at Object.request (.../node_modules/request/index.js:100:12)
    at makeRequest (.../node_modules/@google-cloud/common/node_modules/retry-request/index.js:155:28)
    at Object.retryRequest [as default] (.../node_modules/@google-cloud/common/node_modules/retry-request/index.js:94:5)
    at Util.makeRequest (.../node_modules/@google-cloud/common/src/util.ts:694:26)
    at onAuthenticated (.../node_modules/@google-cloud/common/src/util.ts:614:24)
    at .../node_modules/@google-cloud/common/src/util.ts:626:15
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

### PR DESCRIPTION
**Pull request by JustinBeckwith**
Fixes #185, and you know, all the other upstream modules I broke with 0.20.2.  Synthetic imports offer us very little gain, and lots of pain.

### CODE REVIEW

**Comment by JustinBeckwith** [comment]
TBR = @ofrobots (since this is busted in prod)

**Comment by ofrobots** [comment]
Lgtm
