### ISSUE TITLE
TypeError: method is not a function when calling request (regression from 0.20.1)

### ISSUE THREAD

**Issue by vieira** [googleapis/nodejs-common#185]
- OS: MacOS 10.13.5
  - Node.js version: 10.5.0
  - npm version: N/A
  - @google-cloud/common version: 0.20.2 (works on 0.20.1)

```js
await request({
  method: 'PUT',
  uri: `subscriptions/${this.name}`,
  body: {
    topic: `projects/${projectId}/topics/${topic}`,
    ackDeadlineSeconds: this.ackDeadlineSeconds,
  },
  json: true,
})
```

```
(node:1182) UnhandledPromiseRejectionWarning: TypeError: method is not a function
    at Object.request (.../node_modules/request/index.js:100:12)
    at makeRequest (.../node_modules/@google-cloud/common/node_modules/retry-request/index.js:155:28)
    at Object.retryRequest [as default] (.../node_modules/@google-cloud/common/node_modules/retry-request/index.js:94:5)
    at Util.makeRequest (.../node_modules/@google-cloud/common/src/util.ts:694:26)
    at onAuthenticated (.../node_modules/@google-cloud/common/src/util.ts:614:24)
    at .../node_modules/@google-cloud/common/src/util.ts:626:15
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by JustinBeckwith** [comment]
Thanks for the bug report!  Could you provide a more complete example?  On which module are you calling the `request` method?

**Comment by vieira** [comment]
Hi, sure!

Let me know if the following is enough to get an idea of what I am doing:

```js
import util from 'util';
import Topic from './topic';

const common = require('@google-cloud/common');
const packageJson = require('../package.json');

function PubSub(options) {
  if (!(this instanceof PubSub)) {
    return new PubSub(options);
  }

  const config = {
    baseUrl: `https://pubsub.googleapis.com/v1/projects/${options.projectId}`,
    projectIdRequired: false,
    scopes: [
      'https://www.googleapis.com/auth/iam',
      'https://www.googleapis.com/auth/cloud-platform',
      'https://www.googleapis.com/auth/pubsub',
    ],
    packageJson,
  };

  const normalizedOptions = common.util.normalizeArguments(this, options);
  common.Service.call(this, config, normalizedOptions);
}

util.inherits(PubSub, common.Service);

PubSub.prototype.topic = function (name) {
  return new Topic(this, name);
};

module.exports = PubSub;
```

```js
class Topic {
  constructor(client, name) {
    this.client = client;
    this.name = name;
  }

  async create() {
    try {
      await this.client.request({
        method: 'PUT',
        uri: `topics/${this.name}`,
      });
    } catch (err) {
      if (err.code !== 409) throw err;
    }
    return this;
  }
  // (...)
}

module.exports = Topic;
```

**Comment by stephenplusplus** [comment]
Storage is broken as well: https://circleci.com/gh/googleapis/nodejs-storage/6039
